### ISSUE TITLE
Copyright holder and license

### ISSUE THREAD

**Issue by marcelometal** [globocom/dbaas-credentials#1]
Hi,
Could you please add LICENSE file and put the copyright holder and license inside each file? This way there is no chance of someone stumbling across a piece of code without being exposed to the license.

**Comment by otherpirate** [comment]
Hi @marcelometal

We will add soon, thanks!

**Comment by marcelometal** [comment]
@otherpirate ping?

**Comment by otherpirate** [comment]
Hi @marcelometal, thanks a lot

Sorry, for the delay, I totally forgot this issue

The PR #2 closes this issue
